import { NgModule } from '@angular/core';
import {
    MatDialogModule,
    MatAutocompleteModule,
    MatExpansionModule,
    MatCardModule,
    MatSidenavModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatStepperModule,
    MatBottomSheetModule,
 //   MatProgressBarModule,
    MatChipsModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatDividerModule,
    MatButtonModule,
    MatIconModule,
    MatToolbarModule,
    MatTooltipModule,
    MatBadgeModule,
    MatInputModule,
    MatSelectModule,
    MatRadioModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatGridListModule,
    MatMenuModule,
    MatTabsModule,
    MatSlideToggleModule,
} from '@angular/material';
import { CdkTableModule } from '@angular/cdk/table';
import { A11yModule } from '@angular/cdk/a11y';
import { BidiModule } from '@angular/cdk/bidi';
import { OverlayModule } from '@angular/cdk/overlay';
import { PlatformModule } from '@angular/cdk/platform';
import { ObserversModule } from '@angular/cdk/observers';
import { PortalModule } from '@angular/cdk/portal';

@NgModule({
    exports: [
        MatDialogModule,
        MatExpansionModule,
        MatCardModule,
        MatListModule,
        MatIconModule,
        MatButtonToggleModule,
        MatTabsModule,
        MatProgressSpinnerModule,
        MatSlideToggleModule,
        MatChipsModule,
        MatBottomSheetModule,
        MatToolbarModule,
        MatTooltipModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatBadgeModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatButtonModule,
        MatDividerModule,
        MatInputModule,
        MatSelectModule,
        MatRadioModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatGridListModule,
        MatTabsModule,
        MatMenuModule,
        // Material Modules
        MatAutocompleteModule,
        // MatButtonModule,
        // MatButtonToggleModule,
        // MatCardModule,
        // MatCheckboxModule,
        // MatChipsModule,
        // MatTableModule,
        // MatDatepickerModule,
        // MatDialogModule,
        // MatExpansionModule,
        // MatFormFieldModule,
        // MatGridListModule,
        // MatIconModule,
        // MatInputModule,
        // MatListModule,
        // MatMenuModule,
        // MatPaginatorModule,
       //  MatProgressBarModule,
        // MatProgressSpinnerModule,
        // MatRadioModule,
        // MatRippleModule,
        // MatSelectModule,
        // MatSidenavModule,
        // MatSlideToggleModule,
        // MatSliderModule,
        // MatSnackBarModule,
        // MatSortModule,
        // MatTabsModule,
        // MatToolbarModule,
       //  MatTooltipModule,
        // MatNativeDateModule,
         MatStepperModule,
        // CdkTableModule,
        // A11yModule,
        // BidiModule,
        // ObserversModule,
        // OverlayModule,
        // PlatformModule,
        // PortalModule,
    ],
    declarations: []
})
export class AppMaterialModules { }
