# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Leezed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Leezed
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 5.0'
  pod 'UIGradient', '~> 1.2.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Cosmos', '~> 18.0'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'DropDown', '2.3.4'
  pod 'FBSDKLoginKit', '~> 5.0'
  pod 'ActiveLabel'
  pod 'JWTDecode', '~> 2.4'
  pod 'MMText'
  pod 'Navajo-Swift'

  target 'LeezedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeezedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
